Fix tests
mi-erasmusmc/PatientLevelPrediction pull request #11
Opened 2023-07-26 10:38 UTC by egillax

- skip tests that require github secrets
- Document univariate and stepwise selection, was causing a R cmd check warning

2023-07-27 07:58 UTC, egillax commented
@rossdwilliams can you review? With this PR the tests pass.

2023-07-31 08:39 UTC, rossdwilliams requested changes
can you address the two minor comments then this is good to og

2023-07-31 08:39 UTC, rossdwilliams commented on R/VariableSelection.R
>                                   selectMethod = "backward",
as this is either forward or backward, can you add a check for that?

2023-07-31 08:39 UTC, rossdwilliams commented on R/VariableSelection.R
> +#' @param corMethod which type of correlation to use, default `pearson`
what are the other available options?

2023-07-31 12:54 UTC, egillax commented
Comments have been addressed. Merging.

2023-07-31 12:54 UTC, merged